-- Run once in the Supabase SQL Editor.
-- Personal trips are separate from the imported public route templates.

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  start_date date,
  end_date date,
  status text not null default 'idea' check (status in ('idea', 'planning', 'booked', 'completed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table if not exists public.trip_days (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  day_number integer not null check (day_number > 0),
  date date,
  overnight_city text,
  lodging_name text,
  lodging_url text,
  notes text,
  unique (trip_id, day_number)
);

create table if not exists public.trip_stops (
  id bigint generated by default as identity primary key,
  trip_day_id bigint not null references public.trip_days(id) on delete cascade,
  place_id bigint references public.places(id) on delete set null,
  position integer not null check (position > 0),
  custom_name text,
  planned_time time,
  notes text,
  unique (trip_day_id, position),
  check (place_id is not null or nullif(trim(custom_name), '') is not null)
);

alter table public.trips enable row level security;
alter table public.trip_days enable row level security;
alter table public.trip_stops enable row level security;

grant select, insert, update, delete on public.trips to authenticated;
grant select, insert, update, delete on public.trip_days to authenticated;
grant select, insert, update, delete on public.trip_stops to authenticated;
grant usage, select on sequence public.trips_id_seq to authenticated;
grant usage, select on sequence public.trip_days_id_seq to authenticated;
grant usage, select on sequence public.trip_stops_id_seq to authenticated;

drop policy if exists "admins manage own trips" on public.trips;
create policy "admins manage own trips"
on public.trips for all to authenticated
using (
  owner_id = auth.uid()
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  owner_id = auth.uid()
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage days of own trips" on public.trip_days;
create policy "admins manage days of own trips"
on public.trip_days for all to authenticated
using (
  exists (
    select 1 from public.trips
    where trips.id = trip_days.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1 from public.trips
    where trips.id = trip_days.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage stops of own trips" on public.trip_stops;
create policy "admins manage stops of own trips"
on public.trip_stops for all to authenticated
using (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_stops.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_stops.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create or replace function public.touch_trip_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_table_name = 'trips' then
    new.updated_at = now();
    return new;
  end if;

  update public.trips
  set updated_at = now()
  where id = coalesce(new.trip_id, old.trip_id);
  return null;
end;
$$;

drop trigger if exists touch_trips_updated_at on public.trips;
create trigger touch_trips_updated_at
before update on public.trips
for each row execute function public.touch_trip_updated_at();

create or replace function public.touch_trip_from_stop()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_day_id bigint := coalesce(new.trip_day_id, old.trip_day_id);
begin
  update public.trips
  set updated_at = now()
  where id = (select trip_id from public.trip_days where id = target_day_id);
  return null;
end;
$$;

drop trigger if exists touch_trip_days_updated_at on public.trip_days;
create trigger touch_trip_days_updated_at
after insert or update or delete on public.trip_days
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_stops_updated_at on public.trip_stops;
create trigger touch_trip_stops_updated_at
after insert or update or delete on public.trip_stops
for each row execute function public.touch_trip_from_stop();
