-- Run once in the Supabase SQL Editor.
-- Personal trips are separate from the imported public route templates.

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  start_date date,
  end_date date,
  status text not null default 'idea' check (status in ('idea', 'planning', 'booked', 'completed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table if not exists public.trip_days (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  day_number integer not null check (day_number > 0),
  date date,
  overnight_city text,
  lodging_name text,
  lodging_url text,
  lodging_status text check (lodging_status is null or lodging_status in ('planned', 'booked', 'paid')),
  lodging_source_day_id bigint references public.trip_days(id) on delete set null,
  notes text,
  unique (trip_id, day_number)
);

create table if not exists public.trip_day_transports (
  id bigint generated by default as identity primary key,
  trip_day_id bigint not null references public.trip_days(id) on delete cascade,
  position integer not null check (position > 0),
  mode text not null default 'train' check (mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other')),
  from_name text,
  to_name text,
  details text,
  booking_url text,
  departure_time time,
  arrival_time time,
  booked boolean not null default false,
  paid boolean not null default false,
  unique (trip_day_id, position)
);

create table if not exists public.trip_stops (
  id bigint generated by default as identity primary key,
  trip_day_id bigint not null references public.trip_days(id) on delete cascade,
  place_id bigint references public.places(id) on delete set null,
  position integer not null check (position > 0),
  custom_name text,
  planned_time time,
  notes text,
  admission_status text check (admission_status is null or admission_status in ('planned', 'booked', 'paid')),
  admission_url text,
  unique (trip_day_id, position),
  check (place_id is not null or nullif(trim(custom_name), '') is not null)
);

create table if not exists public.trip_bookings (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  kind text not null default 'other' check (kind in ('lodging', 'transport', 'admission', 'other')),
  title text not null,
  status text not null default 'planned' check (status in ('planned', 'booked', 'paid')),
  date date,
  url text,
  notes text,
  position integer not null check (position > 0),
  unique (trip_id, position)
);

create table if not exists public.trip_destinations (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  trip_day_id bigint references public.trip_days(id) on delete set null,
  name text not null,
  position integer not null check (position > 0),
  latitude double precision,
  longitude double precision,
  notes text,
  unique (trip_id, position),
  check ((latitude is null and longitude is null) or (latitude is not null and longitude is not null))
);

create table if not exists public.trip_legs (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  from_destination_id bigint not null references public.trip_destinations(id) on delete cascade,
  to_destination_id bigint not null references public.trip_destinations(id) on delete cascade,
  mode text not null default 'train' check (mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other')),
  details text,
  departure_time time,
  arrival_time time,
  booked boolean not null default false,
  paid boolean not null default false,
  booking_url text,
  unique (from_destination_id, to_destination_id),
  check (from_destination_id <> to_destination_id)
);

alter table public.trip_legs add column if not exists departure_time time;
alter table public.trip_legs add column if not exists arrival_time time;
alter table public.trip_legs add column if not exists trip_day_id bigint references public.trip_days(id) on delete set null;
alter table public.trip_legs add column if not exists booking_url text;
alter table public.trip_days add column if not exists destination_id bigint references public.trip_destinations(id) on delete set null;
alter table public.trip_days add column if not exists lodging_status text;
alter table public.trip_days add column if not exists lodging_source_day_id bigint references public.trip_days(id) on delete set null;
create index if not exists trip_days_lodging_source_day_id_idx on public.trip_days(lodging_source_day_id);
alter table public.trip_days drop constraint if exists trip_days_lodging_source_not_self;
alter table public.trip_days add constraint trip_days_lodging_source_not_self
  check (lodging_source_day_id is null or lodging_source_day_id <> id);
alter table public.trip_stops add column if not exists admission_status text;
alter table public.trip_stops add column if not exists admission_url text;
alter table public.trip_stops add column if not exists to_transport_mode text
  check (to_transport_mode is null or to_transport_mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other'));
alter table public.trip_stops add column if not exists to_transport_details text;
alter table public.trip_stops add column if not exists to_departure_time time;
alter table public.trip_stops add column if not exists to_arrival_time time;
alter table public.trip_stops add column if not exists back_transport_mode text
  check (back_transport_mode is null or back_transport_mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other'));
alter table public.trip_stops add column if not exists back_transport_details text;
alter table public.trip_stops add column if not exists back_departure_time time;
alter table public.trip_stops add column if not exists back_arrival_time time;
alter table public.trip_destinations add column if not exists trip_day_id bigint references public.trip_days(id) on delete set null;
alter table public.trips add column if not exists home_city text not null default 'Токио';
alter table public.trip_days add column if not exists city_destination_id bigint references public.trip_destinations(id) on delete set null;
alter table public.trip_days add column if not exists transport_mode text not null default 'train'
  check (transport_mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other'));
alter table public.trip_days add column if not exists transport_details text;
alter table public.trip_days add column if not exists transport_booking_url text;
alter table public.trip_days add column if not exists transport_departure_time time;
alter table public.trip_days add column if not exists transport_arrival_time time;
alter table public.trip_days add column if not exists transport_booked boolean not null default false;
alter table public.trip_days add column if not exists transport_paid boolean not null default false;

update public.trip_days as day
set destination_id = destination.id
from public.trip_destinations as destination
where day.destination_id is null
  and day.trip_id = destination.trip_id
  and nullif(trim(day.overnight_city), '') is not null
  and lower(trim(day.overnight_city)) = lower(trim(destination.name));

-- A day's activity city is the previous night's city. For the first day it is
-- the arrival/overnight city. This turns Komatsu → Toyama lodging data into
-- day cities Komatsu, Komatsu, Toyama without duplicating route nodes.
with ordered_days as (
  select id, trip_id, day_number, destination_id,
    lag(destination_id) over (partition by trip_id order by day_number) as previous_destination_id
  from public.trip_days
)
update public.trip_days as day
set city_destination_id = coalesce(ordered.previous_destination_id, ordered.destination_id)
from ordered_days as ordered
where day.id = ordered.id and day.city_destination_id is null;

update public.trip_destinations as destination
set trip_day_id = day.id
from public.trip_days as day
where destination.trip_day_id is null
  and day.destination_id = destination.id
  and day.trip_id = destination.trip_id;

with day_context as (
  select day.*,
    row_number() over (partition by day.trip_id order by day.day_number) as day_index,
    count(*) over (partition by day.trip_id) as day_count
  from public.trip_days as day
)
insert into public.trip_day_transports (
  trip_day_id, position, mode, from_name, to_name, details, booking_url,
  departure_time, arrival_time, booked, paid
)
select context.id, 1, context.transport_mode,
  case when context.day_index = 1 then trip.home_city else city.name end,
  case
    when context.day_index = 1 then city.name
    when context.day_index = context.day_count then trip.home_city
    else overnight.name
  end,
  context.transport_details, context.transport_booking_url,
  context.transport_departure_time, context.transport_arrival_time,
  context.transport_booked, context.transport_paid
from day_context as context
join public.trips as trip on trip.id = context.trip_id
left join public.trip_destinations as city on city.id = context.city_destination_id
left join public.trip_destinations as overnight on overnight.id = context.destination_id
where not exists (
  select 1 from public.trip_day_transports as transport where transport.trip_day_id = context.id
);

alter table public.trips enable row level security;
alter table public.trip_days enable row level security;
alter table public.trip_day_transports enable row level security;
alter table public.trip_stops enable row level security;
alter table public.trip_bookings enable row level security;
alter table public.trip_destinations enable row level security;
alter table public.trip_legs enable row level security;

grant select, insert, update, delete on public.trips to authenticated;
grant select, insert, update, delete on public.trip_days to authenticated;
grant select, insert, update, delete on public.trip_day_transports to authenticated;
grant select, insert, update, delete on public.trip_stops to authenticated;
grant select, insert, update, delete on public.trip_bookings to authenticated;
grant select, insert, update, delete on public.trip_destinations to authenticated;
grant select, insert, update, delete on public.trip_legs to authenticated;
grant usage, select on sequence public.trips_id_seq to authenticated;
grant usage, select on sequence public.trip_days_id_seq to authenticated;
grant usage, select on sequence public.trip_day_transports_id_seq to authenticated;
grant usage, select on sequence public.trip_stops_id_seq to authenticated;
grant usage, select on sequence public.trip_bookings_id_seq to authenticated;
grant usage, select on sequence public.trip_destinations_id_seq to authenticated;
grant usage, select on sequence public.trip_legs_id_seq to authenticated;

drop policy if exists "admins manage own trips" on public.trips;
create policy "admins manage own trips"
on public.trips for all to authenticated
using (
  owner_id = auth.uid()
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  owner_id = auth.uid()
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage days of own trips" on public.trip_days;
create policy "admins manage days of own trips"
on public.trip_days for all to authenticated
using (
  exists (
    select 1 from public.trips
    where trips.id = trip_days.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1 from public.trips
    where trips.id = trip_days.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage transport of own trips" on public.trip_day_transports;
create policy "admins manage transport of own trips"
on public.trip_day_transports for all to authenticated
using (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_day_transports.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_day_transports.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage stops of own trips" on public.trip_stops;
create policy "admins manage stops of own trips"
on public.trip_stops for all to authenticated
using (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_stops.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_stops.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage bookings of own trips" on public.trip_bookings;
create policy "admins manage bookings of own trips"
on public.trip_bookings for all to authenticated
using (
  exists (
    select 1 from public.trips
    where trips.id = trip_bookings.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1 from public.trips
    where trips.id = trip_bookings.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage destinations of own trips" on public.trip_destinations;
create policy "admins manage destinations of own trips"
on public.trip_destinations for all to authenticated
using (
  exists (select 1 from public.trips where trips.id = trip_destinations.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (select 1 from public.trips where trips.id = trip_destinations.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage legs of own trips" on public.trip_legs;
create policy "admins manage legs of own trips"
on public.trip_legs for all to authenticated
using (
  exists (select 1 from public.trips where trips.id = trip_legs.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (select 1 from public.trips where trips.id = trip_legs.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create or replace function public.touch_trip_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_table_name = 'trips' then
    new.updated_at = now();
    return new;
  end if;

  update public.trips
  set updated_at = now()
  where id = case when tg_op = 'DELETE' then old.trip_id else new.trip_id end;
  return null;
end;
$$;

drop trigger if exists touch_trips_updated_at on public.trips;
create trigger touch_trips_updated_at
before update on public.trips
for each row execute function public.touch_trip_updated_at();

create or replace function public.touch_trip_from_stop()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_day_id bigint := case when tg_op = 'DELETE' then old.trip_day_id else new.trip_day_id end;
begin
  update public.trips
  set updated_at = now()
  where id = (select trip_id from public.trip_days where id = target_day_id);
  return null;
end;
$$;

drop trigger if exists touch_trip_days_updated_at on public.trip_days;
create trigger touch_trip_days_updated_at
after insert or update or delete on public.trip_days
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_stops_updated_at on public.trip_stops;
create trigger touch_trip_stops_updated_at
after insert or update or delete on public.trip_stops
for each row execute function public.touch_trip_from_stop();

drop trigger if exists touch_trip_bookings_updated_at on public.trip_bookings;
create trigger touch_trip_bookings_updated_at
after insert or update or delete on public.trip_bookings
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_destinations_updated_at on public.trip_destinations;
create trigger touch_trip_destinations_updated_at
after insert or update or delete on public.trip_destinations
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_legs_updated_at on public.trip_legs;
create trigger touch_trip_legs_updated_at
after insert or update or delete on public.trip_legs
for each row execute function public.touch_trip_updated_at();
