-- Allow any number of ordered transport segments per trip day.
-- Safe to run more than once in the Supabase SQL Editor.

create table if not exists public.trip_day_transports (
  id bigint generated by default as identity primary key,
  trip_day_id bigint not null references public.trip_days(id) on delete cascade,
  position integer not null check (position > 0),
  mode text not null default 'train' check (mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other')),
  from_name text,
  to_name text,
  details text,
  booking_url text,
  departure_time time,
  arrival_time time,
  booked boolean not null default false,
  paid boolean not null default false,
  unique (trip_day_id, position)
);

with day_context as (
  select day.*,
    row_number() over (partition by day.trip_id order by day.day_number) as day_index,
    count(*) over (partition by day.trip_id) as day_count
  from public.trip_days as day
)
insert into public.trip_day_transports (
  trip_day_id, position, mode, from_name, to_name, details, booking_url,
  departure_time, arrival_time, booked, paid
)
select context.id, 1, context.transport_mode,
  case when context.day_index = 1 then trip.home_city else city.name end,
  case
    when context.day_index = 1 then city.name
    when context.day_index = context.day_count then trip.home_city
    else overnight.name
  end,
  context.transport_details, context.transport_booking_url,
  context.transport_departure_time, context.transport_arrival_time,
  context.transport_booked, context.transport_paid
from day_context as context
join public.trips as trip on trip.id = context.trip_id
left join public.trip_destinations as city on city.id = context.city_destination_id
left join public.trip_destinations as overnight on overnight.id = context.destination_id
where not exists (
  select 1 from public.trip_day_transports as transport where transport.trip_day_id = context.id
);

alter table public.trip_day_transports enable row level security;
grant select, insert, update, delete on public.trip_day_transports to authenticated;
grant usage, select on sequence public.trip_day_transports_id_seq to authenticated;

drop policy if exists "admins manage transport of own trips" on public.trip_day_transports;
create policy "admins manage transport of own trips"
on public.trip_day_transports for all to authenticated
using (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_day_transports.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_day_transports.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);
