-- Run once in the Supabase SQL Editor.
-- Personal trips are separate from the imported public route templates.

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  start_date date,
  end_date date,
  status text not null default 'idea' check (status in ('idea', 'planning', 'booked', 'completed')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table if not exists public.trip_days (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  day_number integer not null check (day_number > 0),
  date date,
  overnight_city text,
  lodging_name text,
  lodging_url text,
  notes text,
  unique (trip_id, day_number)
);

create table if not exists public.trip_stops (
  id bigint generated by default as identity primary key,
  trip_day_id bigint not null references public.trip_days(id) on delete cascade,
  place_id bigint references public.places(id) on delete set null,
  position integer not null check (position > 0),
  custom_name text,
  planned_time time,
  notes text,
  unique (trip_day_id, position),
  check (place_id is not null or nullif(trim(custom_name), '') is not null)
);

create table if not exists public.trip_bookings (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  kind text not null default 'other' check (kind in ('lodging', 'transport', 'admission', 'other')),
  title text not null,
  status text not null default 'planned' check (status in ('planned', 'booked', 'paid')),
  date date,
  url text,
  notes text,
  position integer not null check (position > 0),
  unique (trip_id, position)
);

create table if not exists public.trip_destinations (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  name text not null,
  position integer not null check (position > 0),
  latitude double precision,
  longitude double precision,
  notes text,
  unique (trip_id, position),
  check ((latitude is null and longitude is null) or (latitude is not null and longitude is not null))
);

create table if not exists public.trip_legs (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  from_destination_id bigint not null references public.trip_destinations(id) on delete cascade,
  to_destination_id bigint not null references public.trip_destinations(id) on delete cascade,
  mode text not null default 'train' check (mode in ('train', 'bus', 'car', 'flight', 'ferry', 'walk', 'other')),
  details text,
  departure_time time,
  arrival_time time,
  booked boolean not null default false,
  paid boolean not null default false,
  unique (from_destination_id, to_destination_id),
  check (from_destination_id <> to_destination_id)
);

alter table public.trip_legs add column if not exists departure_time time;
alter table public.trip_legs add column if not exists arrival_time time;
alter table public.trip_legs add column if not exists trip_day_id bigint references public.trip_days(id) on delete set null;
alter table public.trip_days add column if not exists destination_id bigint references public.trip_destinations(id) on delete set null;

update public.trip_days as day
set destination_id = destination.id
from public.trip_destinations as destination
where day.destination_id is null
  and day.trip_id = destination.trip_id
  and nullif(trim(day.overnight_city), '') is not null
  and lower(trim(day.overnight_city)) = lower(trim(destination.name));

alter table public.trips enable row level security;
alter table public.trip_days enable row level security;
alter table public.trip_stops enable row level security;
alter table public.trip_bookings enable row level security;
alter table public.trip_destinations enable row level security;
alter table public.trip_legs enable row level security;

grant select, insert, update, delete on public.trips to authenticated;
grant select, insert, update, delete on public.trip_days to authenticated;
grant select, insert, update, delete on public.trip_stops to authenticated;
grant select, insert, update, delete on public.trip_bookings to authenticated;
grant select, insert, update, delete on public.trip_destinations to authenticated;
grant select, insert, update, delete on public.trip_legs to authenticated;
grant usage, select on sequence public.trips_id_seq to authenticated;
grant usage, select on sequence public.trip_days_id_seq to authenticated;
grant usage, select on sequence public.trip_stops_id_seq to authenticated;
grant usage, select on sequence public.trip_bookings_id_seq to authenticated;
grant usage, select on sequence public.trip_destinations_id_seq to authenticated;
grant usage, select on sequence public.trip_legs_id_seq to authenticated;

drop policy if exists "admins manage own trips" on public.trips;
create policy "admins manage own trips"
on public.trips for all to authenticated
using (
  owner_id = auth.uid()
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  owner_id = auth.uid()
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage days of own trips" on public.trip_days;
create policy "admins manage days of own trips"
on public.trip_days for all to authenticated
using (
  exists (
    select 1 from public.trips
    where trips.id = trip_days.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1 from public.trips
    where trips.id = trip_days.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage stops of own trips" on public.trip_stops;
create policy "admins manage stops of own trips"
on public.trip_stops for all to authenticated
using (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_stops.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1
    from public.trip_days
    join public.trips on trips.id = trip_days.trip_id
    where trip_days.id = trip_stops.trip_day_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage bookings of own trips" on public.trip_bookings;
create policy "admins manage bookings of own trips"
on public.trip_bookings for all to authenticated
using (
  exists (
    select 1 from public.trips
    where trips.id = trip_bookings.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (
    select 1 from public.trips
    where trips.id = trip_bookings.trip_id and trips.owner_id = auth.uid()
  )
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage destinations of own trips" on public.trip_destinations;
create policy "admins manage destinations of own trips"
on public.trip_destinations for all to authenticated
using (
  exists (select 1 from public.trips where trips.id = trip_destinations.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (select 1 from public.trips where trips.id = trip_destinations.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

drop policy if exists "admins manage legs of own trips" on public.trip_legs;
create policy "admins manage legs of own trips"
on public.trip_legs for all to authenticated
using (
  exists (select 1 from public.trips where trips.id = trip_legs.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  exists (select 1 from public.trips where trips.id = trip_legs.trip_id and trips.owner_id = auth.uid())
  and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create or replace function public.touch_trip_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_table_name = 'trips' then
    new.updated_at = now();
    return new;
  end if;

  update public.trips
  set updated_at = now()
  where id = case when tg_op = 'DELETE' then old.trip_id else new.trip_id end;
  return null;
end;
$$;

drop trigger if exists touch_trips_updated_at on public.trips;
create trigger touch_trips_updated_at
before update on public.trips
for each row execute function public.touch_trip_updated_at();

create or replace function public.touch_trip_from_stop()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_day_id bigint := case when tg_op = 'DELETE' then old.trip_day_id else new.trip_day_id end;
begin
  update public.trips
  set updated_at = now()
  where id = (select trip_id from public.trip_days where id = target_day_id);
  return null;
end;
$$;

drop trigger if exists touch_trip_days_updated_at on public.trip_days;
create trigger touch_trip_days_updated_at
after insert or update or delete on public.trip_days
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_stops_updated_at on public.trip_stops;
create trigger touch_trip_stops_updated_at
after insert or update or delete on public.trip_stops
for each row execute function public.touch_trip_from_stop();

drop trigger if exists touch_trip_bookings_updated_at on public.trip_bookings;
create trigger touch_trip_bookings_updated_at
after insert or update or delete on public.trip_bookings
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_destinations_updated_at on public.trip_destinations;
create trigger touch_trip_destinations_updated_at
after insert or update or delete on public.trip_destinations
for each row execute function public.touch_trip_updated_at();

drop trigger if exists touch_trip_legs_updated_at on public.trip_legs;
create trigger touch_trip_legs_updated_at
after insert or update or delete on public.trip_legs
for each row execute function public.touch_trip_updated_at();
